[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
# Nếu Dockerfile chính không hoạt động, đổi thành:
# dockerfilePath = "Dockerfile.alternative"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 