[build]
builder = "DOCKERFILE"
# dockerfilePath = "Dockerfile"
# dockerfilePath = "Dockerfile.alternative"
# Sử dụng Dockerfile đơn giản nhất:
dockerfilePath = "Dockerfile.simple"

[deploy]
healthcheckPath = "/Home/Index"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 